included:
  - packages/kirie/native/ios/Kirie/Sources/Kirie
  - packages/kirie/native/ios/Kirie/Tests

excluded:
  - packages/kirie/native/ios/Kirie/Sources/Kirie/KirieBridge.mm
  - packages/kirie/native/ios/Kirie/Sources/Kirie/KiriePlugin.h
  - packages/kirie/native/ios/Kirie/Sources/Kirie/KiriePlugin.mm
  - packages/kirie/native/ios/Kirie/Sources/Kirie/KirieManager.swift

disabled_rules:
  - trailing_comma
  - todo

line_length:
  warning: 140
  error: 200

function_body_length:
  warning: 80
  error: 120

type_body_length:
  warning: 300
  error: 500
