packages:
  - "examples/basic-ipc/web"
  - "examples/eventa-csharp/web"
  - "packages/*"
  - "tests/integration/web-src"

catalog:
  "@biomejs/biome": 2.2.4
  "@moeru/eventa": ^1.0.0-beta.3
  "@types/ini": ^4.1.1
  "@types/node": ^25.6.0
  bumpp: ^11.0.1
  cborg: ^4.5.8
  citty: ^0.2.2
  execa: 9.6.1
  ini: ^7.0.0
  tsdown: ^0.22.2
  typescript: ^6.0.3
  vite: ^8.0.16
  vitest: ^4.0.15
