interface Kirie {
  webview_ready: Signal<[]>;
  text_received: Signal<[string]>;
  ipc_error: Signal<[string]>;

  create_webview(options: Dictionary): void;
  get_launch_option(key: string): string;
  is_available(): boolean;
  send_text(message: string): void;
}

// @gd.eval: # Generated by tstogd from res://src-godot/scripts/main.ts; do not edit.
export class _Main extends Control {
  static readonly page_url = "res://src-web/dist/index.html";
  static readonly dev_web_url_option = "kirie-web-url";

  _kirie = preload<GDScript>("res://addons/kirie/gd_kirie.gd").new() as Kirie;
  _log_lines: PackedStringArray = PackedStringArray();
  _startup_url = _Main.page_url;
  @onready
  _url_input: LineEdit = gd.as(this.get_node("VBoxContainer/UrlInput"), LineEdit) as LineEdit;
  @onready
  _status_label: Label = gd.as(this.get_node("VBoxContainer/StatusLabel"), Label) as Label;
  @onready
  _log_label: Label = gd.as(this.get_node("VBoxContainer/LogLabel"), Label) as Label;

  _ready(): void {
    this._kirie.webview_ready.connect(this._on_webview_ready);
    this._kirie.text_received.connect(this._on_text_received);
    this._kirie.ipc_error.connect(this._on_ipc_error);
    this._startup_url = this._resolve_startup_url();
    this._url_input.text = this._startup_url;

    if (!this._kirie.is_available()) {
      this._set_status("Status: Kirie singleton not available on this platform");
      this._append_log("Kirie singleton is not available");
      return;
    }

    this._set_status("Status: Kirie singleton available");
    this._append_log("Kirie singleton detected");
    this._create_app_webview();
  }

  _resolve_startup_url(): string {
    const launch_web_url = this._resolve_launch_option(_Main.dev_web_url_option);
    if (launch_web_url !== "") {
      this._append_log(gd.ops.rem("%s detected %s", [_Main.dev_web_url_option, launch_web_url]));
      return launch_web_url;
    }

    const web_url = OS.get_environment("KIRIE_WEB_URL").strip_edges();
    if (web_url === "") {
      return _Main.page_url;
    }

    this._append_log(gd.ops.rem("KIRIE_WEB_URL detected %s", web_url));
    return web_url;
  }

  _resolve_launch_option(key: string): string {
    const native_value = this._kirie.get_launch_option(key).strip_edges();
    if (native_value !== "") {
      return native_value;
    }

    const option_prefix = gd.ops.rem("--%s=", key);
    for (const arg of gd.ops.add(OS.get_cmdline_args(), OS.get_cmdline_user_args())) {
      if (arg.begins_with(option_prefix)) {
        return arg.trim_prefix(option_prefix).strip_edges();
      }
    }

    return "";
  }

  _create_app_webview(): void {
    if (!this._kirie.is_available()) {
      return;
    }

    this._set_status("Status: creating app WebView");
    this._append_log(gd.ops.rem("create_webview initial_url=%s", this._startup_url));

    const options = { initial_url: this._startup_url };
    this._kirie.create_webview(options);
  }

  _on_webview_ready(): void {
    this._set_status("Status: WebView ready");
    this._append_log("signal webview_ready");
  }

  _on_text_received(message_text: string): void {
    this._append_log(gd.ops.rem("signal text_received %s", message_text));

    const message = JSON.parse_string(message_text);
    if (!(message instanceof Dictionary)) {
      return;
    }

    const message_type = str(message.get("type", ""));
    if (message_type === "web_ready") {
      this._set_status("Status: received web_ready");
      const reply = { type: "godot_ready", payload: { message: "Hello from Godot" } };
      this._kirie.send_text(JSON.stringify(reply));

      return;
    }
  }

  _on_ipc_error(error: string): void {
    this._set_status("Status: IPC error");
    this._append_log(gd.ops.rem("signal ipc_error %s", error));
  }

  _append_log(line: string): void {
    this._log_lines.append(line);

    while (this._log_lines.size() > 10) {
      this._log_lines.remove_at(0);
    }

    this._log_label.text = gd.ops.add("Log:\n", "\n".join(this._log_lines));
    print(line);
  }

  _set_status(text: string): void {
    this._status_label.text = text;
  }
}
